

version: '2'

services:
  
  falcohm:
    image: node:14.15.1
    container_name: falcohm
    restart: unless-stopped
    ports:
      - 8081:8000
    networks:
      slg-network:
        ipv4_address: 192.168.10.6
    # environment:
    #   SEQ_DB: rent_db
    #   SEQ_USER: userdb
    #   SEQ_PW: xela12899821
    #   PORT: 8000
    #   DATABASE_URL: postgres://userdb:xela12899821@db:5432/mydatabase
    volumes:
      - ../:/var/www/backend
    command: bash -c "cd /var/www/backend && npm i && npm run watch && npm run dev"


  db:
    image: postgres
    container_name: database
    restart: always
    environment:
        POSTGRES_PASSWORD : admin
        # POSTGRES_DB : rent_db
        # POSTGRES_USER : userdb
    logging:
      options:
        max-size: 10m
        max-file: '3'
    networks:
      slg-network:
        ipv4_address: 192.168.10.11
    volumes :
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
 

  caddyWebsite:
    depends_on:
      - falcohm   
    image: caddy:2.3.0
    container_name: caddyWebsite
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    networks:
      slg-network:
        ipv4_address: 192.168.10.7

#--------------------

networks:

    slg-network:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.10.0/24
            gateway: 192.168.10.1
 
